@echo off
echo stop Api.BasicData...
taskkill /f /im DMA.Api.BasicData.exe"
echo stop Api.Device...
taskkill /f /im DMA.Api.Device.exe"
echo stop Api.DeviceData...
taskkill /f /im DMA.Api.DeviceData.exe"
echo stop Api.Fault...
 taskkill /f /im DMA.Api.Fault.exe"
echo stop Api.Security...
taskkill /f /im DMA.Api.Security.exe"
echo stop Api.Subarea...
taskkill /f /im DMA.Api.Subarea.exe"
echo stop Api.DeviceHandle...
taskkill /f /im DMA.Api.DeviceHandle.exe"